### PR TITLE
Enable to config ContainerGCPeriod

### PR DESCRIPTION
**Pull request by houming-wang**
ContainerGCPeriod is the period for performing container garbage collection.
This variable is hard code to 1 minute and can not be configured. But with
init container(s) in Pod, Pod recreation/deletion is slow, because the init
container(s) is(are) deleted by 1 minute interval periodically container
GC task. We make this configurable and defaults to 10 seconds to reduce
Pod recreation/deletion time.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by xxiao93** [comment]
Can one of the admins verify this patch?

**Comment by chestack** [comment]
test this please

**Comment by ypnuaa037** [comment]
maybe this PR (https://github.com/kubernetes/kubernetes/pull/63321) should be merge too
related issue: https://github.com/kubernetes/kubernetes/issues/60518

**Comment by xxiao93** [comment]
test e2e

**Pull request closed without merging**
